$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = breathing, 0.4, 0.0, 0.2, 1.0
    bezier = morning_mist, 0.5, 0.0, 0.0, 1.0
    animation = fade, 1, 10, breathing
    animation = input-field, 1, 5, morning_mist
    animation = inputFieldDots, 1, 4, breathing
}

background {
    monitor =
    path = /home/horizon/.config/hypr/current_wallpaper.png
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/song_status.sh
    color = rgb(dde4e2)
    font_size = 30
    font_family = $font
    position = 0, -50
    halign = center
    valign = top
}

label {
    monitor =
    text = <span font_weight="ultrabold">$TIME</span>
    color = rgb(81d5ce)
    font_size = 150
    font_family = $font

    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:43200000] date +"%A, %d %B"
    color = rgb(81d5ce)
    font_size = 40
    font_family = $font
    position = 0, 120
    halign = center
    valign = center
}

image {
    monitor =
    path = /home/horizon/.config/hypr/avatar.jpg
    size = 200
    rounding = -1
    border_size = 4
    border_color = rgb(81d5ce)
    position = 0, -60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 350, 90
    outline_thickness = 5
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(81d5ce) rgb(b0c9e7) 45deg
    inner_color = rgba(1a2120b3)
    font_color = rgb(dde4e2)
    fade_on_empty = false
    font_family = $font
    placeholder_text = <i><span foreground="##889391">Enter Password</span></i>
    hide_input = false

    fail_color = rgb(ffb4ab) rgb(93000a) 40deg
    fail_text = <i>$PAMFAIL</i>

    position = 0, -250
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[en,ru]
    color = rgb(bec9c7)
    font_size = 25
    position = 0, -340
    halign = center
    valign = center
}

shape {
    monitor =
    size = 4000, 300
    color = rgba(81d5ce4D)
    rounding = 0
    border_size = 0
    rotate = 45
    zindex = -1
    position = 1550, 0
    halign = center
    valign = center
}

shape {
    monitor =
    size = 4000, 240
    color = rgba(b0c9e74D)
    rounding = 0
    border_size = 0
    rotate = 45
    zindex = -1
    position = 1950, 0
    halign = center
    valign = center
}

shape {
    monitor =
    size = 4000, 200
    color = rgba(b0ccc94D)
    rounding = 0
    border_size = 0
    rotate = 45
    zindex = -1
    position = 2280, 0
    halign = center
    valign = center
}
